name: Deploy Personal Dashboard API Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.APP_NAME }}:${{ vars.APP_ENV }}-${{ vars.APP_VERSION }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.APP_NAME }}:${{ vars.APP_ENV }}-${{ vars.APP_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: development

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.APP_NAME }}:${{ vars.APP_ENV }}-${{ vars.APP_VERSION }}
            docker stop ${{ vars.APP_NAME }} || echo "No container to stop"
            docker rm ${{ vars.APP_NAME }} || echo "No container to remove"
            docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.APP_NAME }}:${{ vars.APP_ENV }}-${{ vars.APP_VERSION }} || echo "No image to remove"
            docker run -d --restart always --name ${{ vars.APP_NAME }} -p ${{ vars.HOST_PORT }}:${{ vars.CONTAINER_PORT }} -e ENV=development ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.APP_NAME }}:${{ vars.APP_ENV }}-${{ vars.APP_VERSION }}
