name: Deploy to Development

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.APP_NAME }}:${{ vars.APP_VERSION }}-${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set Environment Variables
        run: echo "IMAGE_NAME=$DOCKER_IMAGE_NAME" >> $GITHUB_ENV

      - name: Copy docker-compose-dev.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose-dev.yml"
          target: "${{ secrets.SERVER_WORK_DIR }}/docker-compose-dev.yml"

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_WORK_DIR }}
            IMAGE_NAME=$IMAGE_NAME docker-compose -f docker-compose-dev.yml pull
            IMAGE_NAME=$IMAGE_NAME docker compose -f docker-compose-dev.yml up -d
